# \u6307\u5B9A\u542F\u7528\u73AF\u5883
spring.profiles.active=@spring.profiles.active@
spring.main.allow-bean-definition-overriding=true

################################################################################################################
###logging (log4j2) \u57FA\u672C\u914D\u7F6E\uFF1A
###http://www.cnblogs.com/yhtboke/p/Mybatis.html
################################################################################################################
logging.config=classpath:conf/log4j2-dev.xml
